language: java
sudo: false
services:
- docker
jdk:
- oraclejdk8
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- "./gradlew jacocoTestReport coveralls"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build/asciidoc/html5/index.html
  on:
    branch: master
env:
  global:
  - secure: Jsqj+uJKdoe9k625XrcxABcIQFcWDrEjGfmRVWq0ezGx9QIzvyx+B53Kp25TqcQIQ1SFQEXTqspK+VeNgl1QkY9dL8qxYMyQBY/XAFMm+PBt95OPAWkU9KiKuXMtXSuKUOHSOn4ggWoTt5WA4gYl1PsSCmD4Yu4h9BHOAUM3EEH4sJHpr2QXX+4TP8suSkvJ1hWsNoaKhZ9xFNkWhf2+tbea5hgV6YfdxdnF+JRsUOgXeV0cD7bBdYPanx+S2/JK3RRfUUcNRwCszggPiArmLs9SwjlKk7DNYJGrxVFvDanNb6cA/cRxKlGeyHoH1uWOR6LsbaxIXt2Lw72iXwvN+w0DaT/mWJFF1NovmJ5fgf2KvvfCcbIdR2l4stMjXbaozQ7mtvRnf3h04S5Wz9/39BufT4dPY3b3eeZuKdgRi58GvPRRqRzIlKeltIxGsVURmWk2KEXICTYVsud+qvVlj1ccK8yuuomCE6vB8e1y9hz/9rplbI5m+UlvaFm5toDKzNJCkXx+R6PnOJLoLQHKGCfCvvAGnmkGQ24973OOt/PjF/xdGi8eEP9deMdOVYzqyfZ2hYpczYDmN8SP14ANZSfQO5C3ZjjANuV3PkqhKWmQ37jbVl6h/07QkcPj2mONqcd+JvhIV55Axxj4iKNv1ldAMBFffeA2Zk5C4/NTsSM=
  - secure: GKd7NjnW2+uD/r+HD72UCc1gkQP4DMkRyM0cG4z8z+fBINsHH21YUcMKGHCKVf4M1n8qLpe3vufwT3OgFyneLzUT3h4udnLI1ssaCN4QMZwAxTCUvZe7ophHs9mjEuup/Zm/1pqIG+evK2EuSnEOYhUVh4kPQQRcJkDuYvsSQin37V4oufJOXFyyMWvE8k2hmD9pcE0Ho2UhUFvKtO+/7oOJKjG8SW4fq08dF1eie/EoqoDV4gz+4wFKpQS3YhUxGXSPWfA4YCHiR3YCwgyoU2+Uqi159c6rhM7hoWdY13aoFXVzCdBanSdNNaS8iOmuODjBooW3bxLTYYvMAuSqPLUYYxCYB2z0Znswg0i7JMOorj88vPiQSzq9+TSpYwHAhrPD1pXrUXUa5O81kqsr7ejyl/rlUmzAqfA6L6LWirN2tlA3cWIxsuZyFuOIs4fPQgrYBQ8Fpk9ziKR1AddEyEuKP3nfojnfVl0pWfPSYxNq4orTWyXQ9lIx/OPvsIcjtsO/4easOrKrB+m2yVa2pkrZjkPgpFyGxFOJ+UX0S/vI6EgUVhBofrLioSO1SEkB3Ej99Ayw1xEm775J0XfLSlqDM5SThO3HpWrpsGz/Gr9xmxegguBtKKz2cjgPr9EKOP6TLHu4pVe7UT0hLFspl0A0De2ctJ4HNO/k8Bum3E8=
  - secure: G8uJ86JdEj9Eez5RU7h2AzNZoA8oOSmGu59+0TBPml/ZKYv26Yxkog1HVIp69cZ9Lv0QGmvyMZAOFVVPvZkFjF2FqZIZdZjrWP6OW8In4VRgNCTi1KTDEYhOUKYJy2yIKM2mREuPtMVHs448F3WP/pcIENaj1zlzxSBCzooP1oZc36Ba/ZIQVfrEIe4Vpt0rW5mI5h51xOJd9kLbWL6UcpuismtxjpmszPd4Rc5A7nrajRwbi7eMjh5U2loSH+zttxq8R3wJZIcpIIxNKM4yKV6bl12+B7XP/CMHNlRpY59U9P4LY0VneizobO6kpB+8sjYOgYN0h0MLc+cKUAmI4nadno8CjJTUN9yLIr69SDP9OEmnNN9SkwLtF+CHUVArq6LPnoI+ioCyk04wc7nmQlVO2BZdxkc8KZ7IUIvL9pHcoBtt4YVWMFkUvBgNyEmh8Hor4Vw8VoHTL9l0mrXBgF5pcjv8k4ObwrIMqq5qhTS8jLrweniGaHB+mVbdPt42WLb+lN4Ny5F6dWMPJ7qQZgqucCd7shq27Sv4oeRJw/Jsmgq7jcqtTbSmtVN6QU8TzigIdaEBEQzDZgxsFwzSifULONECzS0f6MZXgJALZ8KDUKLakoKqehuut1qi6Brf1wuWKs0ukwI+OxZP3wDJ04aZktTGLUo5ib3JljEBd8Q=
  - secure: PeOnzx90Edt85sxDLJCgtHL39Ut5apaOLZEi9A2bfaBXun6o0x/dp3dLu60bHn7Xv8DZUKEiWPhRoNdsMGyC2cKAPU9wYud9mtFQO5dDF6QxiDIEKdkVhMwKliVSZTCIkhy93j26OTzLFyuuh1Aaml+a05WXXdZyQhITn03kGDILCy1YK+0syfMlHn2CXzJrgYVqnnpCKarJXZtonSZUNoAFbGYh+hjOz9Fwb599NoqTJVQv3jl5DXavjWZIsrIL9Bth1bkYQRazc5we5t3xevsBkaH3DzJJ9aPpHXDjRHo6ovvqJjS3hK43cx3PUxFcJdxFzhTYohJF+2DCdOHyfamNqnE58vonNCurELVvKPf5Eum78QQZZwvNYd78/Mglf6TdEQkESE3o89TqzFMvu2Ie9niGp5c8GT/DkeKYLBQJoz7NCAVD/DDij0yH+VdrE+HevRb34Ygh8/fQog4fW22y79Hls2LzPZFJvplXmzIp2TZ3o2UIvm9rtTOwfxiky8a4olTbCsdUNoezrSMLxz/8We5vxFZWcg8F+zBI8QBzWjPqFLVwHy/ZSXsWrQX4d0nnqfuWql8noQFN/OMtMJUOWHHc4ybiXXlTi37RIEFPtSsFsu7uPz6o/+1IywLpz6+YYbu0k8aI6uM9Mq9D84AVTznx6dU+gmRE9IQEDRA=
